/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherSubmissionsRouteImport } from './routes/teacher.submissions'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherNotificationsRouteImport } from './routes/teacher.notifications'
import { Route as TeacherLateRequestsRouteImport } from './routes/teacher.late-requests'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as TeacherAiAdvisoryRouteImport } from './routes/teacher.ai-advisory'
import { Route as StudentSubmissionsRouteImport } from './routes/student.submissions'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentLateRequestsRouteImport } from './routes/student.late-requests'
import { Route as StudentFeedbackRouteImport } from './routes/student.feedback'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSubmissionsRoute = TeacherSubmissionsRouteImport.update({
  id: '/teacher/submissions',
  path: '/teacher/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/teacher/profile',
  path: '/teacher/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherNotificationsRoute = TeacherNotificationsRouteImport.update({
  id: '/teacher/notifications',
  path: '/teacher/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLateRequestsRoute = TeacherLateRequestsRouteImport.update({
  id: '/teacher/late-requests',
  path: '/teacher/late-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/teacher/assignments',
  path: '/teacher/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAiAdvisoryRoute = TeacherAiAdvisoryRouteImport.update({
  id: '/teacher/ai-advisory',
  path: '/teacher/ai-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSubmissionsRoute = StudentSubmissionsRouteImport.update({
  id: '/student/submissions',
  path: '/student/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/student/notifications',
  path: '/student/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLateRequestsRoute = StudentLateRequestsRouteImport.update({
  id: '/student/late-requests',
  path: '/student/late-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentFeedbackRoute = StudentFeedbackRouteImport.update({
  id: '/student/feedback',
  path: '/student/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/student/assignments',
  path: '/student/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/admin/teachers',
  path: '/admin/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/admin/subjects',
  path: '/admin/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/late-requests': typeof StudentLateRequestsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/submissions': typeof StudentSubmissionsRoute
  '/teacher/ai-advisory': typeof TeacherAiAdvisoryRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/late-requests': typeof TeacherLateRequestsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/late-requests': typeof StudentLateRequestsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/submissions': typeof StudentSubmissionsRoute
  '/teacher/ai-advisory': typeof TeacherAiAdvisoryRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/late-requests': typeof TeacherLateRequestsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/subjects': typeof AdminSubjectsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/late-requests': typeof StudentLateRequestsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/submissions': typeof StudentSubmissionsRoute
  '/teacher/ai-advisory': typeof TeacherAiAdvisoryRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/late-requests': typeof TeacherLateRequestsRoute
  '/teacher/notifications': typeof TeacherNotificationsRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/submissions': typeof TeacherSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/student/assignments'
    | '/student/dashboard'
    | '/student/feedback'
    | '/student/late-requests'
    | '/student/notifications'
    | '/student/profile'
    | '/student/submissions'
    | '/teacher/ai-advisory'
    | '/teacher/assignments'
    | '/teacher/dashboard'
    | '/teacher/late-requests'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/student/assignments'
    | '/student/dashboard'
    | '/student/feedback'
    | '/student/late-requests'
    | '/student/notifications'
    | '/student/profile'
    | '/student/submissions'
    | '/teacher/ai-advisory'
    | '/teacher/assignments'
    | '/teacher/dashboard'
    | '/teacher/late-requests'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/submissions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/student/assignments'
    | '/student/dashboard'
    | '/student/feedback'
    | '/student/late-requests'
    | '/student/notifications'
    | '/student/profile'
    | '/student/submissions'
    | '/teacher/ai-advisory'
    | '/teacher/assignments'
    | '/teacher/dashboard'
    | '/teacher/late-requests'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentFeedbackRoute: typeof StudentFeedbackRoute
  StudentLateRequestsRoute: typeof StudentLateRequestsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSubmissionsRoute: typeof StudentSubmissionsRoute
  TeacherAiAdvisoryRoute: typeof TeacherAiAdvisoryRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherLateRequestsRoute: typeof TeacherLateRequestsRoute
  TeacherNotificationsRoute: typeof TeacherNotificationsRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherSubmissionsRoute: typeof TeacherSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/submissions': {
      id: '/teacher/submissions'
      path: '/teacher/submissions'
      fullPath: '/teacher/submissions'
      preLoaderRoute: typeof TeacherSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/teacher/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/notifications': {
      id: '/teacher/notifications'
      path: '/teacher/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof TeacherNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/late-requests': {
      id: '/teacher/late-requests'
      path: '/teacher/late-requests'
      fullPath: '/teacher/late-requests'
      preLoaderRoute: typeof TeacherLateRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/teacher/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/ai-advisory': {
      id: '/teacher/ai-advisory'
      path: '/teacher/ai-advisory'
      fullPath: '/teacher/ai-advisory'
      preLoaderRoute: typeof TeacherAiAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/submissions': {
      id: '/student/submissions'
      path: '/student/submissions'
      fullPath: '/student/submissions'
      preLoaderRoute: typeof StudentSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/late-requests': {
      id: '/student/late-requests'
      path: '/student/late-requests'
      fullPath: '/student/late-requests'
      preLoaderRoute: typeof StudentLateRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/feedback': {
      id: '/student/feedback'
      path: '/student/feedback'
      fullPath: '/student/feedback'
      preLoaderRoute: typeof StudentFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/student/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/admin/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubjectsRoute: AdminSubjectsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentFeedbackRoute: StudentFeedbackRoute,
  StudentLateRequestsRoute: StudentLateRequestsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSubmissionsRoute: StudentSubmissionsRoute,
  TeacherAiAdvisoryRoute: TeacherAiAdvisoryRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherLateRequestsRoute: TeacherLateRequestsRoute,
  TeacherNotificationsRoute: TeacherNotificationsRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherSubmissionsRoute: TeacherSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
